---
- name: Include OS Specific setup tasks.
  include: "setup-{{ ansible_os_family }}.yml"

- name: Include SSL tasks.
  include: ssl.yml

- name: Include Plugin tasks.
  include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
